name: "[CD] Continuous Delivery"

on:
    pull_request:
        types: [opened, synchronize]
env: 
    VERCEL_TOKEN: 86CrvP84Vv43xBnxEkDC01q6
    VERCEL_ORG_ID: team_F3vI9A3Wf18BuhcEunF5ytdG
    VERCEL_PROJECT_ID: prj_diUnFj0p0gk5Qzfg6ce9eQhuAEK3
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            ## [Commom_CI_Steps]
            - uses: actions/checkout@v3
            ##=====================
            - name: "Debug"
              run: "ls -la"
            - name: "Install Dependecies"
              run: "npm install"
            - name: "Deploy"
              run: "npx vercel --prod"
