name: "[CD] Continuous Delivery"

on:
    pull_request:
        types: [opened, synchronize]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            ## [Commom_CI_Steps]
            - uses: actions/checkout@v3
            ##=====================
            - name: "Debug"
              run: "ls -la"
            - name: "Install Dependecies"
              run: "npm install"
            - name: "Lint"
              run: "npx vercel --prod --token=86CrvP84Vv43xBnxEkDC01q6"
